=== gravitee-io/gravitee-access-management/gravitee-am-reporter/gravitee-am-reporter-kafka/src/test/resources/json/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Audit Message Value Dto",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "transactionId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "type": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "referenceType": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "referenceId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "accessPoint": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/AuditAccessPointDto"
        }
      ]
    },
    "actor": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/AuditEntityDto"
        }
      ]
    },
    "target": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "$ref": "#/definitions/AuditEntityDto"
        }
      ]
    },
    "status": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "timestamp": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "integer",
          "format": "utc-millisec"
        }
      ]
    },
    "environmentId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "organizationId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "domainId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "nodeId": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    },
    "nodeHostname": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "string"
        }
      ]
    }
  },
  "definitions": {
    "AuditAccessPointDto": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "alternativeId": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "displayName": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "ipAddress": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "userAgent": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      }
    },
    "AuditEntityDto": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "alternativeId": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "type": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "displayName": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "referenceType": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        },
        "referenceId": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "string"
            }
          ]
        }
      }
    }
  }
}

=== gravitee-io/gravitee-access-management/gravitee-am-reporter/gravitee-am-reporter-kafka/src/test/resources/json/audit.json
{
  "id": "id",
  "transactionId": "transaction id",
  "type": "type",
  "referenceType": "APPLICATION",
  "referenceId": "reference id",
  "accessPoint": {
    "id": "access point id",
    "alternativeId": "access point alternative id",
    "displayName": "access Display Name",
    "ipAddress": "192.168.1.1",
    "userAgent": "Chrome"
  },
  "actor": {
    "id": "actor id",
    "alternativeId": "actor alternative id",
    "type": "actor type",
    "displayName": "actor display name",
    "referenceType": "APPLICATION",
    "referenceId": "actor reference id"
  },
  "target": {
    "id": "target id",
    "alternativeId": "target alternative id",
    "type": "target type",
    "displayName": "target display name",
    "referenceType": "APPLICATION",
    "referenceId": "target reference id"
  },
  "status": "status",
  "timestamp": "1970-01-01T00:00:00Z",
  "environmentId": "DEFAULT",
  "organizationId": "DEFAULT",
  "nodeId": "node-id",
  "nodeHostname": "main.srv.local"
}
